---

- name: should have some base packages
  become: true
  action: >
    apt name={{ item }} state=present update_cache=yes
  with_items:
    - vim
    - git
    - zsh
    - logrotate
    - tmux

- name: set default shell to zsh for root
  user:
    user: root
    shell: /usr/bin/zsh
